### ISSUE TITLE
Google Group-button跳转有误

### ISSUE THREAD

**Issue by Muyun99** [NUAA-Open-Source/a2os_index#5]
1. 右上角以及左边列表"联系我们"一栏中的的Google Group的Button跳转链接有误
2. ( 另外，之前的blogroll的link不加上了吗
3. Members的link也有误

**Comment by ghost** [comment]
1. 这个我在新的pr中修复了

**Comment by RayZhao1998** [comment]
BlogRoll 将作为 A2OS 的项目展示在主页上
